CREATE USER sa WITH PASSWORD '123456';
CREATE DATABASE teddy;
CREATE DATABASE teddy_test;

GRANT ALL PRIVILEGES ON DATABASE teddy TO sa;
GRANT ALL PRIVILEGES ON DATABASE teddy_test TO sa;

ALTER USER sa WITH SUPERUSER;
