version: '3'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app
    networks:
      - app-network
    container_name: back

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=5173
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - app-network
    container_name: front

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back
    networks:
      - app-network
    container_name: nginx

networks:
  app-network:
    driver: bridge
