export const text = {
  CLEAR_SELECTED_CLIENTS_SUCCESS: 'Os clientes selecionados foram removidos!',
  COPY_EMAIL_ERROR: 'Erro ao copiar email para a área de transferência!',
  COPY_EMAIL_SUCCESS: 'Email copiado para a área de transferência!',
  COPY_WHATSAPP_ERROR: 'Erro ao copiar whatsapp para a área de transferência!',
  COPY_WHATSAPP_SUCCESS: 'Whatsapp copiado para a área de transferência!',
  CREATE_CLIENT_ERROR: 'Erro ao criar cliente!',
  CREATE_CLIENT_SUCCESS: 'Cliente criado com sucesso!',
  CREATE_USER_ERROR: 'Erro ao criar usuário!',
  CREATE_USER_SUCCESS: 'Usuário criado com sucesso!',
  DELETE_CLIENT_ERROR: 'Erro ao deletar cliente!',
  DELETE_CLIENT_SUCCESS: 'Cliente deletado com sucesso!',
  DELETE_SELECTED_CLIENT_SUCCESS: 'Cliente removido com sucesso!',
  DELETE_USER_SUCCESS: 'Usuário deletado com sucesso!',
  EMAIL_ALREADY_EXISTS: 'E-mail já cadastrado!',
  INTERNAL_SERVER_ERROR: 'Erro interno do servidor!',
  LOGIN_ERROR: 'Erro ao fazer login!',
  LOGIN_INVALID_CREDENTIALS: 'E-mail ou senha inválidos!',
  LOGIN_SUCCESS: 'Login realizado com sucesso!',
  LOGIN_USER_NOT_FOUND: 'Usuário não encontrado!',
  LOGOUT_ERROR: 'Erro ao fazer logout!',
  LOGOUT_SUCCESS: 'Logout realizado com sucesso!',
  SELECT_CLIENT_SUCCESS: 'Cliente adicionado com sucesso!',
  UPDATE_CLIENT_ERROR: 'Erro ao atualizar cliente!',
  UPDATE_CLIENT_SUCCESS: 'Cliente atualizado com sucesso!'
}
