export const text = {
  CREATE_USER_SUCCESS: 'Usuário criado com sucesso!',
  LOGIN_SUCCESS: 'Login realizado com sucesso!',
  LOGOUT_SUCCESS: 'Logout realizado com sucesso!',
  DELETE_USER_SUCCESS: 'Usuário deletado com sucesso!',
  SELECT_CLIENT_SUCCESS: 'Cliente adicionado com sucesso!',
  DELETE_SELECTED_CLIENT_SUCCESS: 'Cliente removido com sucesso!',
  CREATE_CLIENT_SUCCESS: 'Cliente criado com sucesso!',
  DELETE_CLIENT_SUCCESS: 'Cliente deletado com sucesso!',
  UPDATE_CLIENT_SUCCESS: 'Cliente atualizado com sucesso!',
  CLEAR_SELECTED_CLIENTS_SUCCESS: 'Os clientes selecionados foram removidos!',
  CREATE_USER_ERROR: 'Erro ao criar usuário!',
  LOGIN_ERROR: 'Erro ao fazer login!',
  LOGOUT_ERROR: 'Erro ao fazer logout!',
  CREATE_CLIENT_ERROR: 'Erro ao criar cliente!',
  DELETE_CLIENT_ERROR: 'Erro ao deletar cliente!',
  UPDATE_CLIENT_ERROR: 'Erro ao atualizar cliente!',
  COPY_EMAIL_SUCCESS: 'Email copiado para a área de transferência!',
  COPY_EMAIL_ERROR: 'Erro ao copiar email para a área de transferência!',
  COPY_WHATSAPP_SUCCESS: 'Whatsapp copiado para a área de transferência!',
  COPY_WHATSAPP_ERROR: 'Erro ao copiar whatsapp para a área de transferência!'
}
